#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Feb 06 12:55:05 CET 2022
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ddaab0da7aa849d8a031a88c75fd1459 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot bcd_tb_behav xil_defaultlib.bcd_tb -log elaborate.log"
xelab -wto ddaab0da7aa849d8a031a88c75fd1459 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot bcd_tb_behav xil_defaultlib.bcd_tb -log elaborate.log

